### ISSUE TITLE
Incompability with c2me

### ISSUE THREAD

**Issue by AntonIXO** [daPoseidonGuy/strawgolem#114]
**Game Info**
Game Version : 1.19.2
Mod Version : latest september build
Mod Loader : fabric

**Describe the bug**
Crash: https://pastebin.com/HCKNKhjr

**To Reproduce**
Install c2me mod.
Use farm mechanics.

**Additional context**
I think it is c2me multithreading problem.
Try to change LevelReader to WorldGenRegion in[ this line](https://github.com/t2pellet/strawgolem/blob/c53070cb3ced247b9b87340902548e186da77925/Common/src/main/java/com/t2pellet/strawgolem/crop/CropRegistryImpl.java#L38)

Also update your github repo to the latest code version.

**Comment by t2pellet** [comment]
C2me is experimental, will not be explicitly supported, this is far from the only mod it breaks
