### ISSUE TITLE
Log spam when repeatedly bonemealing Bakery's strawberries

### ISSUE THREAD

**Issue by ryleu** [daPoseidonGuy/strawgolem#142]
https://mclo.gs/KxPATCV

Sometimes this also crashes the game. If you have a mod that lets you right click to harvest, it makes this way easier.

Relevant mods:
- strawgolem v2.0.1-alpha
- fabric v0.15.7
- minecraft v1.19.2
- [bakery](https://modrinth.com/mod/lets-do-bakery) v1.0.6

**Comment by t2pellet** [comment]
should be fixed in new alpha 2.1.0.
(feel free to reopen otherwise)
