### ISSUE TITLE
Straw golem union

### ISSUE THREAD

**Issue by JaisDK** [daPoseidonGuy/strawgolem#2]
I think the golems are forming a union. They are gathering in groups in the corner of my labor camp and refusing to work.
It could also just be that they really want to get to the pumpkins on the other side of the fence...

![2020-06-14_18 01 11](https://user-images.githubusercontent.com/15868585/84597002-8edf0100-ae69-11ea-8f68-5b30d061485d.png)

Maybe make them ignore farmables placed by players or get them to ignore what they can't pathfind to.

Love the mod, they are very adorable!

**Comment by daPoseidonGuy** [comment]
They're most likely trying to get the pumpkins.

I am thinking about redoing the harvest and delivery AI goals and will take this into account for the new implementations.

**Comment by daPoseidonGuy** [comment]
Okay so for now I've simply added a check to ensure they don't try to get crops they cannot reach, which seems to work (although it has introduced some small bugs I'd like to fix before releasing an update)

**Comment by daPoseidonGuy** [comment]
The aforementioned implementation solves this issue with my testing. Will be released in the next update
