### ISSUE TITLE
Golems not moving to chest on their own

### ISSUE THREAD

**Issue by Areolata7** [daPoseidonGuy/strawgolem#4]
I recently started using this mod and used it on an existing 1.14.4 world and they work perfectly. I just started a new 1.14 world, with the exact same mod set, and they are not behaving the same in this new world. 

On the new world they pick the crop and then just stand there staring. If I physically push them a few blocks towards the chest they eventually go to the chest, put the item in the chest, return to pick something else, and then just stand there again until I push them. They are on the top level of a building and I made sure the config was set to vertical search of 3 blocks and horizontal of 20 so there is no way they are seeing any other chests besides the one on that top floor. I had no such issue on the first world so I have no idea what to do. 

--I broke the chest and placed it back
--I made two more golems right next to the chest (thinking the first two were somehow broken) 
--The chest does attach to a hopper system that takes the items down to the lowest level of the building. However, I have a hopper system on the first world and it does not interfere with functionality so I do not think the hopper presence is the issue.
--I removed the chests on the floor below them just to make sure they were not interferring.
--I removed the column in the center of the garden (see pic) just in case it was ruining their "line of sight". 
---The chest is right behind me in the pic of the single golem with the wheat. It is next to the fence but has 5 blocks open on the other 3 sides so there is nothing obstructing its access. 

I do not know what else to try. Please advise. 

1.14.4
forge 28.2.0
I was using strawgolem 1.14.4-1.7 (for both worlds) but I just updated today to 1.7.1 and I see no changes; they are still not going to the chest on their own. 

Also; are the golems supposed to be active as long as the chunk is loaded or do they require the player to be within a specific distance? I am most often on the bottom floor of the building (level 66) and this garden area is at level 95. I am wondering if my distance keeps stalling them out.

![2020-07-04_05 40 08](https://user-images.githubusercontent.com/56558824/86512575-fe8d3f80-bdc8-11ea-81b8-1da966c95f7f.png)
![2020-07-04_05 39 55](https://user-images.githubusercontent.com/56558824/86512580-077e1100-bdc9-11ea-826b-e6bd7be71eb9.png)

**Comment by daPoseidonGuy** [comment]
> Also; are the golems supposed to be active as long as the chunk is loaded or do they require the player to be within a specific distance? I am most often on the bottom floor of the building (level 66) and this garden area is at level 95. I am wondering if my distance keeps stalling them out.

As long as the chunk is loaded should be fine

Apologies for the issue you are having.

Strange that it would only happen on a new world.

Do the golems have line of sight on the chest?

**Comment by Areolata7** [comment]
I played around and fixed it but it still doesn't seem right. I had to move it over 2 and up 1 in order for the golems to use it (see pic). So now it is raised up on a hopper which is not what I wanted. Again my config settings were for 3 block vertical search and 20 block horizontal - so that chest was well within their search area. Why does it have to be as I have it now?  

Also this garden is only 9x6. My other world has a much larger garden (20x20) and the chest is located on one corner. I never adjusted the config file for that one and the golems have no issue with walking all the way to the far corner and getting back to the chest. 

![2020-07-06_09 29 10](https://user-images.githubusercontent.com/56558824/86794229-e0764800-c031-11ea-8ff0-2c8cc9a88ef8.png)

**Comment by daPoseidonGuy** [comment]
Probably the line of sight checks are being problematic, they seem to fire even for things like iron bars, or anything with even a partial collision box.
I'll be changing the way I implement it next update.
Just in case, try increasing the vertical search range to 4 or 5? See if that solves the problem?
