### ISSUE TITLE
Iron Chests Support

### ISSUE THREAD

**Issue by WenXin20** [daPoseidonGuy/strawgolem#5]
`Minecraft v1.15.2`
`Straw Golem v1.7.1`

As soon as I upgraded my chest to an Iron Chest, the Straw Golem no longer recognizes it and will not place crops in it. If I place a normal chest back down, it will place the crops in that one instead.

**Comment by daPoseidonGuy** [comment]
This is surprising - i thought i already had compatibility with any modded chests

Perhaps i screwed something up by accident in an update somewhere..

Looking into it!

**Comment by WenXin20** [comment]
Thanks! It works with the wood chests from Quark, but not the Iron Chests

**Comment by daPoseidonGuy** [comment]
Yea - I looked at it - iron chests dont seem to extend the vanilla TileEntityChest - I've generalized the way it works now so it's fixed for the next update :) 

Sorry the next update is taking so long, there's a few things I'm ironing out and I've been busy with school and such

**Comment by WenXin20** [comment]
It's no problem, take as long as you need!
