### ISSUE TITLE
Issue with the newest version of the 1.9-beta

### ISSUE THREAD

**Issue by Absurde** [daPoseidonGuy/strawgolem#6]
Ever since I updated the beta version whenever I reload the world after about 5 seconds everything sort of stops. I can move around, but can't interact with most objects/mobs, mobs don't move/turn/do anything, the blocks I break vanish and so on. If I remove the mod it goes back to normal, and if I then reintroduce it the problem's back. This doesn't happen on the first time I enter a world when I run minecraft, only once I go back to the menu and try to get back in.
This problem wasn't present with the first version of the 1.9-beta that was released yesterday, I've reloaded my world with that one many times, it's only once I updated today that this issue cropped up. It might be linked to the features (shivering, lifespan changes due to water) that you mentioned were fixed in this one.

Edit: I can also confirm that disabling the shivering and all the lifespan penalties in the config does not remove the bug.

**Comment by daPoseidonGuy** [comment]
Oh no!

Can you check to see if this happens on a fresh world?

Also, try typing /forge tps in your world when it freezes. I'm assuming its something with tps but I just want to make sure.

Its strange to see this, I tested to make sure there's no issues and double checked it today, I can't seem to reproduce this on my end.

Finally, try disabling golemInteract in the config?

**Comment by Absurde** [comment]
Hey, here's what I found:

New worlds indeed don't have this problem. Several reloads with straw and iron golems present and it continues to work. I'm not sure if it might be the number of villagers in my vicinity in the old world that could be the cause or what. Really unfortunate.

By the time things freeze the forge command doesn't return anything, but that's because no command does.

Disabling golemInteract didn't affect things either. Even tried disabling all the options under Misc and Lifespan and the issue persisted.

I then went back to the previous version you sent me and I find the same thing happening there now too. I'm 100% certain that I reloaded with this one a bunch the night it was released. 

This really bothered me so I did some more digging for anything I could think of.
Went back to the current version, but loaded an old backup from before I added the mod in the first place. And the bug initially didn't happen. Reloaded a couple times, seemed to work, but then I closed minecraft completely, reopened it and tried loading that save a couple times again. And on the second time it was loaded, stuff froze again. Same with even older backups.

At some point I tested if /gamerule doDaylightCycle false had an effect since I had it set in the current save and a couple of backups, and it sort of looked like turning it on in the new world made things freeze.. but then I did some more testing of new worlds and it ended up looking irrelevant. 
I used the same procedure every time: cheats enabled, create world, make small farm, spawn a golem, place a chest, set priority with wheat, bonemeal the crops to start things rolling. Then exited to the menu and went back in.
The results were sort of hit and miss for some reason. Sometimes it worked, even on completely restarting minecraft, sometimes it froze right on the second reload without needing to restart the game. It doesn't seem like the whole restarting minecraft has an effect in the end. It might, but it's so erratic that it could well be a coincidence. I genuinely can't figure out a common element that could be triggering this. Espeically since none of this happens if I go back to 1.7.1 in any world, old, the new ones I conducted tests in that were previously frozen, or brand new.

Hope something in this wall of my mad ramblings is of use to you, but I really don't wanna drive you insane trying to pick this apart. If it's irreproducible on your end it could just be an idiosyncrasy of my constellation of mods or even a problem with my system somehow. It genuinely wouldn't be the first time >_<

**Comment by daPoseidonGuy** [comment]
I have a guess as to what it may be. I'll keep you posted. For now, probably best to use the latest release version.

**Comment by Absurde** [comment]
Cool, will do. And if you need any more testing done just say the word.

**Comment by daPoseidonGuy** [comment]
Just a warning the turnaround time for this might be longer than usual just because end of semester is nearing and the workload is piling up a bit

**Comment by Absurde** [comment]
No worries at all, school should definitely come first! You get to it when you get to it :D

**Comment by daPoseidonGuy** [comment]
Hey! If you don't mind, with the problematic version of the mod, try the following:

- Load a world until/to confirm it freezes after 5 seconds (the issue presents itself)
- Close the world
- Go to the world save location, the data folder and delete strawgolem.dat
- Reload the world
- See if the issue is still there

**Comment by Absurde** [comment]
Ok, here's how it went:
Put in the newest beta and entered my world. Waited a few seconds, closed the world. Went back in, waited to see all the mobs freeze and checked to make sure things weren't functioning, then closed the world again. Here's the issue I forgot to mention before: when the freeze happens I'm unable to exit the world to the main menu, the saving never finishes. So if you needed me to not close the game while deleting the .dat file, it's unfortunately not possible.
In any case, I proceeded to terminate the process, restarted the game, and re-entered the world. Didn't delete the .dat file yet at this point since I wanted to test if the once frozen world does work again on the first load as was the case with previous tests, and it did. Now I closed the world, deleted the .dat file and re-entered. Unfortunately it didn't make a difference, things froze a couple of seconds into entering anyway.

**Comment by daPoseidonGuy** [comment]
Try with this:
https://drive.google.com/file/d/1N1mgBqGbawZgWC8lwJX468HBfHIiqcCw/view?usp=sharing

Let me know how it goes :)

**Comment by Absurde** [comment]
It seems whatever you did fixed it! Several reloads and game restarts, no freezing :D Thanks a lot for your hard work!

**Comment by daPoseidonGuy** [comment]
Great! I changed the way golems harvest crops again :p
I just want to see how this system performs in the long term (i.e. if golems will continue to harvest crops quickly without missing any)
