### ISSUE TITLE
[MC 1.15.2][1.9-beta] Unresponsive Server After Disconnecting in Nether

### ISSUE THREAD

**Issue by wchen1990** [daPoseidonGuy/strawgolem#7]
Here's the crash report:
https://mc.rocketnotfound.com/crash-2020-08-01_00.28.46-server.txt

I've been playing on my Minecraft server for a while with Straw Golems running while I was in the overworld for some time now and haven't had issues until now. I finally got around to going to the Nether and I signed out momentarily to do something else. I come back and try to connect to my server to discover that the server crashed because it took too long to process a tick. I started up the server again and I got a crash report similar to the one I linked above.

I tried the JAR file that was linked in #6 and that didn't seem to resolve the issue. The crash report linked is the one generated using the JAR file found in that issue.

For now removing the mod from my server is my only solution at the moment. But, it'd be great to have the cute guy back.

I did some looking at the relevant files and I can't see anything wrong but I'm not exactly a Minecraft mod developer.

If you need any more information from me, please let me know.

**Comment by daPoseidonGuy** [comment]
Hmm.

Okay! I'll take a look at it.

Progress is slower as of late since I'm busy with school, but I'll be back to regular development the 13th of August.

For now use the latest release build!

**Comment by daPoseidonGuy** [comment]
Hey! Tell me if this fixes your issue? 

https://drive.google.com/file/d/1kuV5tsUQ5d5IvtSG9R1gD8J7I-QdrY1r/view?usp=sharing

**Comment by wchen1990** [comment]
It seems to be working fine right now.

Put it on my server, restarted it, and made the little guy again. Made sure
he knows where the treasure chest is and then I went off into the Nether
and disconnected in there. Server was still up and running and responsive.
Hopefully, this solves this issue.

Thanks for your help on this!

**Comment by daPoseidonGuy** [comment]
No problem!
