### ISSUE TITLE
[1.15.2] [1.9-beta] Straw Golem attempts to insert items on full containers, destroying the item

### ISSUE THREAD

**Issue by vectorwing** [daPoseidonGuy/strawgolem#8]
Hello there! I found a quick issue when testing the beta version, regarding full containers.

### Description
When a Straw Golem has an item to deliver, and the exposed slots on the targeted container are full (hopper, furnace etc), the golem will insert the item anyway, **destroying it** without any changes to the container's stored items. Breaking the container does not yield the extra items the golem tried to insert.

Also, probably unrelated, but whenever the golem harvests a mature Sweet Berry Bush, the following line shows up in the console:

`[Server thread/WARN] [minecraft/TrackedEntity]: Fetching packet for removed entity ItemEntity['Sweet berries'/137, l='New World', x=9.73, y=56.68, z=13.68]`

### Steps to Reproduce
1. Spawn a Straw Golem next to a container that is full (furnace with input, a full hopper etc) and no other containers nearby;
2. Grow a mature crop near it, watch it harvest and deliver the items to the container.

### Mod List
Forge 31.2.31 (old latest) or 31.2.36 (new latest)
strawgolem-1.15.2-1.9-beta

**Comment by daPoseidonGuy** [comment]
> [Server thread/WARN] [minecraft/TrackedEntity]: Fetching packet for removed entity ItemEntity['Sweet berries'/137, l='New World', x=9.73, y=56.68, z=13.68]

Yea, I've noticed this and it bugs me too. It's harmless though.

As for the main issue here, I will have it fixed for the next update! (Should come in a week or so?)
